### ISSUE TITLE
UWP ARM64 Build Support

### ISSUE THREAD

**Issue by shibayan** [ericsink/SQLitePCL.raw#254] opened 2019-02-15 08:07 UTC
Hi. Do you have plan for UWP ARM64 support?

The following error is output by WACK.

```
API sqlite3_aggregate_context in e_sqlite3.dll is not supported for this application type.
API sqlite3_aggregate_count in e_sqlite3.dll is not supported for this application type.
API sqlite3_backup_finish in e_sqlite3.dll is not supported for this application type.
...
```

If you need to modify the build script, I'm thinking of contributing.
Thanks.

**Comment by ericsink** [comment] 2019-02-15 22:43
Hmmm.  Yes, I do want to support this.

FYI, the build scripts for the native code are over in my ericsink/cb repo.

I'll investigate what it will take to add arm64 support.

Thanks.

**Comment by shibayan** [comment] 2019-02-16 05:30
Thank you. You can build to ARM64 from Visual Studio 2017 15.9 or later.

I modified the build script and made it correspond to VS2017 and ARM64. (I have not verified library)

https://github.com/ericsink/cb/compare/master...shibayan:arm64
(Build result : https://ci.appveyor.com/project/shibayan/cb/builds/22417311)

Checking the PE header makes it ARM64.

![image](https://user-images.githubusercontent.com/1356444/52894990-b7fc6c80-31f6-11e9-852d-06041b0e9fe1.png)

**Comment by ericsink** [comment] 2019-03-02 05:00
@shibayan Nice work.  

I've integrated your changes to cb.cs over in my cb repo.  I do still need to do some testing on the builds.

Thanks for your help on this.

**Comment by marswe** [comment] 2019-06-06 19:40
@ericsink do you have a preview version of a SQLitePCLRaw.lib.e_sqlite3.v141 package with ARM64 support ready for people to try out?  Or is there more work required to build such a package?

Thanks

**Comment by ericsink** [comment] 2019-06-06 19:49
Not yet.  :-(

I should have tried to include the ARM64 UWP e_sqlite3.dll in the 1.1.14 release I just did.  I think it would be fairly straightforward to drop it into the nuspec file.

I *do* have that build included in the packaging for my v2 release, but that is under development and no packages have been released yet.

**Comment by marswe** [comment] 2019-06-06 20:45
Would you drop the ARM64 UWP e_sqlite3.dll into the SQLitePCLRaw.lib.e_sqlite3.v140 package or would you create a new package for the v141 toolset?

**Comment by ericsink** [comment] 2019-06-06 20:50
For the 1.x branch, I would drop it into the v140 package.

In the v2 branch, the naming of the packages is different.  The Visual Studio toolset name does not appear in the package names anymore.

**Comment by marswe** [comment] 2019-06-06 21:18
Got it, thanks.  Last question from me then: with the 1.1.14 release just a day old, when do you think would be the next opportunity to update the v140 package with ARM64?

**Comment by ericsink** [comment] 2019-06-06 21:22
I don't know yet.

It shouldn't be too much longer before a have a v2 preview release out.

For 1.x, I will plan to go ahead and drop the build in soon, so that when I do the next release, that part will already be done.

**Comment by cghersi** [comment] 2019-08-03 17:53
Hey Eric, can I try to use v2 in pre-release (2.0.0-pre20190628101813 from nuget) in order to support my ARM64 deployment?

**Comment by ericsink** [comment] 2019-08-04 04:06
That depends on what wrapper you are using around SQLitePCLRaw.  If it's EF Core (or Microsoft.Data.SQLite) then yes, use their 3.0 preview.

If you're using sqlite-net or Akavache, then no, neither of them are updated for SQLitePCLRaw 2.0 yet.

If you have no wrapper and are coding to SQLitePCLRaw directly, then yes, but there are some minor breaking changes.  I can help work through them.

**Comment by cghersi** [comment] 2019-08-05 16:15
My library that uses the SQLite NuGet package is a /NETStandard 2.0 C# library.
The app that is using such library is an UWP app, again in C#.
I had to go thru few changes in the code, but as of now, at least from a compilation perspective I should be good to go. My question is more on the runtime, should I expect any kind of problems, especially on the following:
- deploying on ARM64 vs x64
- running the app on ARM64 vs x64

**Comment by ericsink** [comment] 2019-08-05 16:26
I would expect no problems at that level, but I haven't actually tried running the arm64 builds.

If you want to look at the builds yourself, they're in the ericsink/cb repo.  For example, see `bld/bin/e_sqlite3/win/v141/plain/arm64` in that repo.

**Comment by cghersi** [comment] 2019-08-05 16:27
ok great thanks!

**Comment by RehanSaeed** [comment] 2019-08-12 13:10
I'm using `Microsoft.Data.SQLite` but am unsure about using a preview in production. Are there any plans to backport this fix to the 1.1.x version of SQLite?

**Comment by ericsink** [comment] 2019-08-12 13:21
This is the kind of change I could probably backport to 1.1.x without too much pain.  I'll take a look at doing so, but no promises.

It is my understanding that Microsoft.Data.SQLite 3.0 will be released in just a few weeks from now.

**Comment by RehanSaeed** [comment] 2019-08-12 13:31
Trying to upgrade to the latest version `3.0.0-preview7.19362.6` of `Microsoft.Data.SQLite` causes these warnings to appear when building my ARM64 app:

```
19>C:\Users\foo\.nuget\packages\microsoft.net.native.compiler\2.2.3\tools\Microsoft.NetNative.targets(801,5): warning :
       MCG : warning MCG0004: The method 'sqlite3_key' was not found in module 'e_sqlite3' specified by DllImport method 'System.Int32 SQLitePCL.SQLite3Provider_e_sqlite3.NativeMethods.sqlite3_key(SQLitePCL.sqlite3, System.Byte*, System.Int32)'. Calling this method would throw exception at runtime.
19>C:\Users\foo\.nuget\packages\microsoft.net.native.compiler\2.2.3\tools\Microsoft.NetNative.targets(801,5): warning :
       MCG : warning MCG0004: The method 'sqlite3_key_v2' was not found in module 'e_sqlite3' specified by DllImport method 'System.Int32 SQLitePCL.SQLite3Provider_e_sqlite3.NativeMethods.sqlite3_key_v2(SQLitePCL.sqlite3, System.Byte*, System.Byte*, System.Int32)'. Calling this method would throw exception at runtime.
19>C:\Users\foo\.nuget\packages\microsoft.net.native.compiler\2.2.3\tools\Microsoft.NetNative.targets(801,5): warning :
       MCG : warning MCG0004: The method 'sqlite3_rekey' was not found in module 'e_sqlite3' specified by DllImport method 'System.Int32 SQLitePCL.SQLite3Provider_e_sqlite3.NativeMethods.sqlite3_rekey(SQLitePCL.sqlite3, System.Byte*, System.Int32)'. Calling this method would throw exception at runtime.
19>C:\Users\foo\.nuget\packages\microsoft.net.native.compiler\2.2.3\tools\Microsoft.NetNative.targets(801,5): warning :
       MCG : warning MCG0004: The method 'sqlite3_rekey_v2' was not found in module 'e_sqlite3' specified by DllImport method 'System.Int32 SQLitePCL.SQLite3Provider_e_sqlite3.NativeMethods.sqlite3_rekey_v2(SQLitePCL.sqlite3, System.Byte*, System.Byte*, System.Int32)'. Calling this method would throw exception at runtime.
```

Also, running my app against this version causes the following exception:

```
    Exception thrown: 'Microsoft.Data.Sqlite.SqliteException' in Microsoft.Data.Sqlite.dll
SQLite Error 14: 'unable to open database file'.
```

**Comment by cghersi** [comment] 2019-08-13 20:08
I updated the Nuget package to official release v.2.0.0, but now I am hitting a couple of warning of this type:

> The method 'sqlite3_key' was not found in module 'e_sqlite3' specified by DllImport method 'System.Int32 SQLitePCL.SQLite3Provider_e_sqlite3.NativeMethods.sqlite3_key(SQLitePCL.sqlite3, System.Byte*, System.Int32)'. Calling this method would throw exception at runtime.

This happens only when I build the package for ARM64.

How can I fix this problem?

**Comment by ericsink** [comment] 2019-08-13 20:13
@cghersi  Have a look at the stuff directly above your comment.  Issue #286 is what you're seeing I think.  I haven't confirmed, but I suspect this to be a UWP-specific bug of mine.  Fix pending as soon as I can.

**Comment by cghersi** [comment] 2019-08-13 20:37
@ericsink thanks, I will wait for that fix. Note that my app on x64 works perfectly, while on ARM64 crashes (silently). Code is exactly the same for the two architectures.
I will be happy to provide further info if needed.

**Comment by ericsink** [comment] 2019-08-13 20:39
@cghersi I'll keep that in mind. Not sure my diagnosis is correct yet, but I'll dig into it and figure it out.

**Comment by cghersi** [comment] 2019-08-13 20:41
Great thanks. Let me know if/when there is a preview release that fixes this issue please.

**Comment by ericsink** [comment] 2019-08-15 18:47
@cghersi There's a prerelease for you to try:

https://www.nuget.org/packages/SQLitePCLRaw.lib.e_sqlite3/2.0.1-pre20190815133105

You only need to update SQLitePCLRaw.lib.e_sqlite3

Let me know if it helps?

**Comment by myokeeh** [comment] 2019-08-20 18:00
I recently discovered that adding the pre release version above allows my UWP app to run on ARM64.

Somewhat off topic: How do I reconcile this? Is there a way to specify the prerelease NuGet packages for ARM64 only and not x64?

> Severity	Code	Description	Project	File	Line	Suppression State
Error		Payload contains two or more files with the same destination path 'e_sqlite3.dll'. Source files: 
C:\Users\[User]\.nuget\packages\sqlitepclraw.lib.e_sqlite3\2.0.1-pre20190815133105\runtimes\win10-x64\nativeassets\uap10.0\e_sqlite3.dll
C:\Users\[User]\.nuget\packages\sqlitepclraw.lib.e_sqlite3.v140\1.1.2\runtimes\win10-x64\native\e_sqlite3.dll	[REDACTED]

**Comment by ericsink** [comment] 2019-08-20 18:09
It's good to hear that the ARM64 native code build in that prerelease is working for you. 

(@cghersi Is that prerelease working for you?)

However, you are mixing SQLitePCLRaw 2.x stuff with pre-2.x stuff.  That's generally not advisable, but it happens to be working for you because you're only dealing with the native code builds.

If you want to continue down that (not ideal) path, one way to resolve the problem you're seeing might be to explicitly exclude the 1.x nuget package that contains the native code builds.  Something like this:

```
<PackageReference Include="SQLitePCLRaw.lib.e_sqlite3.v140">
  <Version>1.*</Version>
  <ExcludeAssets>All</ExcludeAssets>
</PackageReference>
```

**Comment by myokeeh** [comment] 2019-08-20 18:23
Getting into more unfamiliar territory. I do want to go by good practice. Is this more of a sit and wait and perhaps I don't even have to specifically add this package when ARM64 e_sqlite3.dll is added?

My UWP app use the following packages which depend on SQLite:
Microsoft.AppCenter.Analytics
Microsoft.Azure.Mobile.Client.SQLiteStore

I'm currently targeting x64 and ARM64. It would be nice to avoid having to cherry pick.

**Comment by ericsink** [comment] 2019-08-20 18:31
In general, you want to wait until whatever libraries you use that depend on SQLitePCLRaw get updated to SQLitePCLRaw 2.0.

I just logged #288 for the AppCenter dependency.

However, I'm not sure the Azure Mobile Apps libraries will get updated.  I believe Microsoft has stopped new work on that product.

So you would want to stay with SQLitePCLRaw 1.x.  However, you need ARM64.

Let me see if I can figure out a better solution for that case.

**Comment by myokeeh** [comment] 2019-08-29 18:46
@ericsink, I'd be very interested in a solution regarding Azure Mobile Apps until AppCenter folks figure out their "Data" product that could potentially replace it.

**Comment by cghersi** [comment] 2019-09-05 23:34
> @cghersi There's a prerelease for you to try:
> 
> https://www.nuget.org/packages/SQLitePCLRaw.lib.e_sqlite3/2.0.1-pre20190815133105
> 
> You only need to update SQLitePCLRaw.lib.e_sqlite3
> 
> Let me know if it helps?

@ericsink we are just using the NuGet package SQLitePCLRaw.bundle_e_sqlite3. We don't use the lib. Could you provide a pre-release of the SQLitePCLRaw.bundle_e_sqlite3 package please?

**Comment by ericsink** [comment] 2019-09-05 23:40
(1) SQLitePCLRaw.bundle_e_sqlite3 does bring in SQLitePCLRaw.lib.e_sqlite3 as a dependency.

(2) Since I posted the note about that pre-release, 2.0.1 has shipped, which contains UWP ARM64 fixes.  Try that instead.

**Comment by RehanSaeed** [comment] 2019-09-06 10:08
I've upgraded Microsoft.Data.Sqlite to 3.0.0-preview9 but am still getting WACK errors:

```
Successfully reset the testing configuration.
    Beginning execution of task Detect app type from package.
    Task Detect app type from package execution result was success.
    Note: Test application type - Centennial.
    Note: Running tests without application deployment.
    Beginning execution of task Clear the network isolation loopback exemption.
    Beginning execution of task Extract files from package.
    Task Clear the network isolation loopback exemption execution result was success.
    Task Extract files from package execution result was success.
    Beginning execution of task Performs app package deployment/cleanup in the IDE scenario..
    Beginning execution of task Modify status of the TAEF service.
    Task Modify status of the TAEF service execution result was success.
    Task Performs app package deployment/cleanup in the IDE scenario. execution result was success.
    Beginning execution of task Program inventory.
    Task Program inventory execution result was success.
    Beginning execution of task App resources.
    Beginning execution of task File association verbs.
    Task App resources execution result was success.
    Task File association verbs execution result was success.
    Beginning execution of task Registry checks.
    Beginning execution of task Decompress app files.
    Task Decompress app files execution result was success.
    Task Registry checks execution result was success.
    Beginning execution of task Enterprise Features.
    Beginning execution of task ExclusiveTo attribute.
    Task Enterprise Features execution result was success.
    Task ExclusiveTo attribute execution result was success.
    Beginning execution of task Type location.
    Beginning execution of task Type name case-sensitivity.
    Task Type location execution result was success.
    Task Type name case-sensitivity execution result was success.
    Beginning execution of task Type name correctness.
    Beginning execution of task General metadata correctness.
    Task Type name correctness execution result was success.
    Task General metadata correctness execution result was success.
    Beginning execution of task Properties.
    Beginning execution of task Banned file analyzer.
    Task Properties execution result was success.
    Task Banned file analyzer execution result was success.
    Beginning execution of task Resource Packages.
    Beginning execution of task Install signed driver and executable files.
Ignoring whitelisted failure: File AdaptiveCards.Rendering.Uwp.dll contains a blocked executable reference to "Dnx".
Ignoring whitelisted failure: File Cortana.dll contains a blocked executable reference to "CMD".
Ignoring whitelisted failure: File Cortana.dll contains a blocked executable reference to "CSI".
WARNING: WACK Test reported failure, see report uploaded to build summary.
```

Is this expected? Do I need to wait for the final release?

**Comment by cghersi** [comment] 2019-09-08 03:11
@ericsink pre-release 2.0.2 made the error disappear for me. Thanks!

**Comment by ericsink** [comment] 2019-09-08 03:25
@RehanSaeed Those WACK errors don't seem to be related to SQLitePCLRaw or even Microsoft.Data.SQLite.

**Comment by RehanSaeed** [comment] 2019-09-09 09:36
Apologies, copying from Azure Pipelines seems broken and some lines were omitted. I've now updated the WACK output above.

@cghersi suggests that `2.0.2` fixes the issue, will Microsoft.Data.Sqlite be updated with this version?

**Comment by ericsink** [comment] 2019-09-09 16:52
(1)  To be clear, if 2.0.2-pre fixed the UWP ARM64 problem, then 2.0.1 also fixes it.  Version 2.0.1 contained fixes for UWP ARM64 stuff.  Version 2.0.2-pre currently contains no changes except support for Apple TvOS.

(2)  SQLitePCLRaw 2.x is supported by Microsoft.Data.SQLite 3.0, which is currently in preview and nearing final release.  Microsoft.Data.SQLite 2.x requires SQLitePCLRaw 1.x.

**Comment by ericsink** [comment] 2019-09-09 17:17
But the WACK errors involving memset/memcmp/etc in vcruntime140.dll are something I have not seen before.  Are these errors still a problem with 2.0.1 ?

**Comment by RehanSaeed** [comment] 2019-09-10 10:01
Yes, those WACK errors came from a UWP app built using `Microsoft.Data.Sqlite` `3.0.0-preview9`.

**Comment by ericsink** [comment] 2019-09-10 14:55
@RehanSaeed That's not what I was asking.  I need to know which of my e_sqlite3 builds you are actually using when you get those WACK errors that mention memset/memcmp and so on.

If you are just using 3.0.0-preview9 of M.D.SQLite and you have not specified a different version number for SQLitePCLRaw, then you are using SQLitePCLRaw 2.0.0, because that's the version M.D.SQLite 3.0 preview 9 transitively brings in.  This is my suspicion about what is happening here.

Try updating SQLitePCLRaw to 2.0.1 and see if the problem goes away.

**Comment by RehanSaeed** [comment] 2019-09-11 15:34
I was under the impression that `3.0.0-preview9` was using `SQLitePCLRaw` version `2.0.1` due to your earlier comment.

> That depends on what wrapper you are using around SQLitePCLRaw. If it's EF Core (or Microsoft.Data.SQLite) then yes, use their 3.0 preview.

Have now also added the v2.0.1 of the `SQLitePCLRaw` package and it seems to fix the WACK errors. So thank you!

**Comment by ericsink** [comment] 2019-09-11 15:41
Ah, sorry for the misunderstanding.  Glad it's working now.  Thanks.

**Comment by myokeeh** [comment] 2019-10-10 22:36
> However, I'm not sure the Azure Mobile Apps libraries will get updated. I believe Microsoft has stopped new work on that product.
> 
> So you would want to stay with SQLitePCLRaw 1.x. However, you need ARM64.
> 
> Let me see if I can figure out a better solution for that case.

@ericsink have you looked into the Azure Mobile Apps problem? I don't want it to suddenly break. Maybe it won't, but I don't know enough about how these things work together to tell. Would forking that project to attempt to keep it up-to-date for myself something that you advise (or advise against)? I'm probably underestimating the work involved.

**Comment by shibayan** [comment] 2019-11-09 11:16
I confirmed that it works properly on Surface Pro X (ARM64).
Thank you for your great work.

**Closed** 2019-12-20 03:05 UTC
