### ISSUE TITLE
Universal Windows Platform: Unable to load DLL 'esqlite3'

### ISSUE THREAD

**Issue by vborovikov** [ericsink/SQLitePCL.raw#84] opened 2016-07-08 17:00 UTC
The library can't properly load the native DLL if SQLite-net is only used in a referenced class library.

Steps to reproduce in VS 2015 Update 3:

- Create blank UWP app App1
- Create UWP class library ClassLibrary1
- Add reference to ClassLibrary1 in App1
- Add Nuget package *sqllite-net-pcl* to ClassLibrary1
- Modify code for `Class1` in ClassLibrary1
```csharp
    public class Class1 : IDisposable
    {
        private readonly SQLiteConnection conn;

        public Class1()
        {
            this.conn = new SQLiteConnection(Path.Combine(Windows.Storage.ApplicationData.Current.LocalFolder.Path, "db.dat"));
        }

        public void Dispose()
        {
            this.conn.Dispose();
        }
    }
```
- Modify code for `MainPage` in App1
```csharp
    public sealed partial class MainPage : Page
    {
        private readonly Class1 class1;

        public MainPage()
        {
            this.InitializeComponent();

            this.class1 = new Class1();
        }
    }
```
- Compile and run App1

App1 will fail with the following exception:

```
System.TypeInitializationException was unhandled by user code
  HResult=-2146233036
  Message=The type initializer for 'SQLite.SQLiteConnection' threw an exception.
  Source=SQLite-net
  TypeName=SQLite.SQLiteConnection
  StackTrace:
       at SQLite.SQLiteConnection..ctor(String databasePath, Boolean storeDateTimeAsTicks)
       at ClassLibrary1.Class1..ctor()
       at App1.MainPage..ctor()
       at App1.App1_XamlTypeInfo.XamlTypeInfoProvider.Activate_0_MainPage()
       at App1.App1_XamlTypeInfo.XamlUserType.ActivateInstance()
  InnerException: 
       HResult=-2146233052
       Message=Unable to load DLL 'esqlite3': Не найден указанный модуль. (Exception from HRESULT: 0x8007007E)
       Source=SQLitePCLPlugin_esqlite3
       TypeName=""
       StackTrace:
            at SQLitePCL.SQLite3Provider_esqlite3.NativeMethods.sqlite3_win32_set_directory(UInt32 directoryType, String directoryPath)
            at SQLitePCL.SQLite3Provider_esqlite3..ctor()
            at SQLitePCL.Batteries.Init()
            at SQLite.SQLiteConnection..cctor()
       InnerException: 
```

**Comment by ericsink** [comment] 2016-07-08 17:23
(Thanks for the excellent writeup with repro steps.)

If you also add a reference to the sqlite-net-pcl nuget package to the app itself, does it work?  If so, this is expected (but somewhat unfortunate) behavior.

**Comment by vborovikov** [comment] 2016-07-08 18:06
It does work if I reference sqlite-net-pcl in the app project. Referencing SQLitePCL.bundle_green works too.

Tried this workaround in a real app, same result.

**Comment by ericsink** [comment] 2016-07-28 15:13
Closing this issue as being "not a bug".  Reopen it if I am misunderstanding something.

**Closed by ericsink** 2016-07-28 15:13 UTC

**Comment by mawarnes** [comment] 2017-05-19 15:28
@ericsink Hi Eric, i'm getting this error to, trying to use it in a WPF application, can't seem to figure out how to get around it....totally stuck

**Comment by ericsink** [comment] 2017-05-19 15:36
@mawarnes This (almost one year old) bug is about a UWP problem.  You say you're in a WPF app.  Your error may be similar to the one this bug is about, but it's not the same.  For example, does your error message say "esqlite3", or does it say "e_sqlite3", with an underscore?  I need the exact error message.  I need to know what version you're using.
