### ISSUE TITLE
Overall result is Failed in Windows App Certification Kit process. (UWP) (API ... is not supported)

### ISSUE THREAD

**Issue by AlirezaP** [ericsink/SQLitePCL.raw#210] opened 2018-03-28 14:02 UTC
hi
When "Compile With .Net Native Tool Chain" is enabled and the configuration is adjusted in to release mode
for creating UWP package
Overall result is Failed in Windows App Certification Kit process.

Supported API test
Error Found: The supported APIs test detected the following errors:

> API CryptGenRandom in advapi32.dll is not supported for this application type. sqlcipher.dll calls this API.
> API AreFileApisANSI in kernel32.dll is not supported for this application type. sqlcipher.dll calls this API.
> API CompareStringW in kernel32.dll is not supported for this application type. sqlcipher.dll calls this API.
> API CreateFileA in kernel32.dll is not supported for this application type. sqlcipher.dll calls this API.
> API CreateFileMappingW in kernel32.dll is not supported for this application type. sqlcipher.dll calls this API.
> API CreateFileW in kernel32.dll is not supported for this application type. sqlcipher.dll calls this API.
> API ExitProcess in kernel32.dll is not supported for this application type. sqlcipher.dll calls this API.
> API GetFileSize in kernel32.dll is not supported for this application type. sqlcipher.dll calls this API.
> API GetModuleHandleExW in kernel32.dll is not supported for this application type. sqlcipher.dll calls this API.
> API GetModuleHandleW in kernel32.dll is not supported for this application type. sqlcipher.dll calls this API.
> API GetOEMCP in kernel32.dll is not supported for this application type. sqlcipher.dll calls this API.
> API GetStartupInfoW in kernel32.dll is not supported for this application type. sqlcipher.dll calls this API.
> API HeapValidate in kernel32.dll is not supported for this application type. sqlcipher.dll calls this API.
> API LCMapStringW in kernel32.dll is not supported for this application type. sqlcipher.dll calls this API.
> API LoadLibraryA in kernel32.dll is not supported for this application type. sqlcipher.dll calls this API.
> API LoadLibraryExW in kernel32.dll is not supported for this application type. sqlcipher.dll calls this API.
> API LoadLibraryW in kernel32.dll is not supported for this application type. sqlcipher.dll calls this API.
> API MapViewOfFile in kernel32.dll is not supported for this application type. sqlcipher.dll calls this API.
> API UnhandledExceptionFilter in kernel32.dll is not supported for this application type. sqlcipher.dll calls this API.
> API VirtualLock in kernel32.dll is not supported for this application type. sqlcipher.dll calls this API.
> API VirtualUnlock in kernel32.dll is not supported for this application type. sqlcipher.dll calls this API.

Impact if not fixed: Using an API that is not part of the Windows SDK for Windows Store apps violates the Windows Store certification requirements.

**Comment by ericsink** [comment] 2018-03-28 14:54
Duplicate of #193 

This should be fixed in version 1.1.0, which was just pushed up to nuget.org.

**Closed by ericsink** 2018-03-28 14:54 UTC

**Comment by AlirezaP** [comment] 2018-03-28 16:54
Thank you.
