### ISSUE TITLE
1.1.9 breaks net46 consumer

### ISSUE THREAD

**Issue by kentcb** [ericsink/SQLitePCL.raw#205] opened 2018-03-13 23:54 UTC
Hello,

I use a net46 build for unit tests, so that my tests can exercise Akavache logic in my code base. When 1.1.9 was released, affected tests started failing with:

```
System.TypeInitializationException: The type initializer for 'Akavache.Sqlite3.Internal.SQLiteConnection' threw an exception.
   at Akavache.Sqlite3.Internal.SQLiteConnection..ctor(String databasePath, Boolean storeDateTimeAsTicks)
   at Akavache.Sqlite3.SQLitePersistentBlobCache..ctor(String databaseFile, IScheduler scheduler)
   at Akavache.Sqlite3.SQLiteEncryptedBlobCache..ctor(String databaseFile, IEncryptionProvider encryptionProvider, IScheduler scheduler)
   at Akavache.Sqlite3.Registrations.<>c__DisplayClass0_0.<Register>b__4()
   at System.Lazy`1.CreateValue()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Lazy`1.get_Value()
   at Akavache.Sqlite3.Registrations.<>c__DisplayClass0_0.<Register>b__5()
   at Splat.ModernDependencyResolver.GetService(Type serviceType, String contract)
   at Splat.DependencyResolverMixins.GetService[T](IDependencyResolver This, String contract)
   at Akavache.BlobCache.get_Secure()
   at <<redacted>>.Services.Connected.Session.Authentication.AuthenticationProvider.<>c__DisplayClass9_0.<AuthenticateLocal>b__0() in C:\Users\kent\Repository\<<redacted>>\Src\Services.Connected\Session\Authentication\AuthenticationProvider.cs:line 121
   at System.Reactive.Linq.ObservableImpl.Defer`1.Eval()
   at System.Reactive.Linq.ObservableImpl.Defer`1._.Run()
--- End of stack trace from previous location where exception was thrown ---
   at System.Reactive.PlatformServices.ExceptionServicesImpl.Rethrow(Exception exception)
   at System.Reactive.ExceptionHelpers.ThrowIfNotNull(Exception exception)
   at System.Reactive.Subjects.AsyncSubject`1.GetResult()
   at <<redacted>>.Services.Connected.Session.Authentication.AuthenticationProvider.<>c__DisplayClass8_0.<<Authenticate>b__0>d.MoveNext() in C:\Users\kent\Repository\<<redacted>>\Src\Services.Connected\Session\Authentication\AuthenticationProvider.cs:line 69
--- End of stack trace from previous location where exception was thrown ---
   at System.Reactive.PlatformServices.ExceptionServicesImpl.Rethrow(Exception exception)
   at System.Reactive.ExceptionHelpers.ThrowIfNotNull(Exception exception)
   at System.Reactive.Linq.QueryLanguage.LastOrDefaultInternal[TSource](IObservable`1 source, Boolean throwOnEmpty)
   at System.Reactive.Linq.QueryLanguage.Wait[TSource](IObservable`1 source)
   at System.Reactive.Linq.Observable.Wait[TSource](IObservable`1 source)
   at <<redacted>>.UnitTests.Services.Session.Authentication.AuthenticationProviderFixture.authenticate_passes_<<redacted>>in C:\Users\kent\Repository\<<redacted>>\Src\UnitTests\Services\Session\Authentication\AuthenticationProviderFixture.cs:line 54
System.DllNotFoundException: Unable to load DLL 'e_sqlite3': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at SQLitePCL.SQLite3Provider_e_sqlite3.NativeMethods.sqlite3_libversion_number()
   at SQLitePCL.SQLite3Provider_e_sqlite3.SQLitePCL.ISQLite3Provider.sqlite3_libversion_number()
   at SQLitePCL.raw.SetProvider(ISQLite3Provider imp)
   at SQLitePCL.Batteries_V2.Init()
   at Akavache.Sqlite3.Internal.SQLiteConnection..cctor()
```

If I take an explicit dependency on 1.1.8 instead, all my tests work again.

Looking at my build output in both scenarios, building against 1.1.8 _does_ copy the `e_sqlite3.dll` file to an `x86` (and `x64`) subfolder in my output directory. Building against 1.1.9 does not.

Given how long 1.1.9 has been out, I suspect I might be just misunderstanding how things work now...any thoughts?

**Comment by ericsink** [comment] 2018-03-14 00:25
That is rather surprising.

To confirm my recollection, I just reviewed all the diffs between 1.1.8 and 1.1.9, and I don't see anything that seems related to what you are describing.  All I see are:

1.  Some changes which are specific to sqlcipher
2.  Some changes for Mac/Xamarin
3.  Some changes for that are specific to UWP
4.  The addition of a Windows build for ARM

And it looks pretty clear from your description and error message that you're on net46/Windows.

So this steers me toward suspicions of weird stuff.  Like, maybe clean your build dir and package dir, re-fetch, and see if it happens again?

**Comment by ericsink** [comment] 2018-03-14 23:30
Hmph. 

I'll try to reproduce the problem and see what happens.

**Comment by ericsink** [comment] 2018-03-16 17:17
So just to confirm:  Using VS 2017, I created a net46 console app, added SQLitePCLRaw.bundle_e_sqlite3 1.1.9, and wrote a bit of code in Program.cs to use it.  Build and run, and the code works, and e_sqlite3.dll lands in the right places in the output dir.

So it seems like something in your case is different from what I just did, and in such a way that 1.1.8 vs 1.1.9 is relevant.

So, random diagnostic questions:

Are you using PackageReference or packages.config or what?

Is your build config AnyCPU, or x64, or what?

**Comment by kentcb** [comment] 2018-03-18 23:04
OK, I just went to repro the problem for you in a separate project:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net46;netstandard1.3</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="1.1.9" />
  </ItemGroup>

</Project>
```
This seemed to work fine. I then tried picking up the dependency transitively via Akavache:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net46;netstandard1.3</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Akavache" Version="6.0.0-alpha0038" />
  </ItemGroup>

</Project>
```
This does not work.

Confusingly, I went back to my prior project and changed the 1.1.8 dependency to 1.1.9, and that continued to work. And that's when I realized that I don't think I ever _tried_ an explicit 1.1.9 dependency before reporting the issue (sorry). Instead, I was just relying on the fact that Akavache was picking it up by default.

So....I think the problem has morphed from "1.1.9 doesn't work" to "explicit dependency required when using 1.1.9 where it wasn't required with 1.1.8". Smells like a NuGet bug to me, but perhaps there's a slight packaging difference that is causing the problem...?

**Comment by ericsink** [comment] 2018-03-20 15:32
I'm trying to confirm that 1.1.9 behaves differently than 1.1.8 in cases where it is a transitive dependency, but I'm not seeing it.

In your second csproj above (the one which references Akavache), it is version 1.1.8 of SQLitePCLRaw that gets transitively referenced, right?

When I build this csproj, I do not get x64/x86 subdirs in the build output directory.

**Comment by kentcb** [comment] 2018-03-21 04:24
OK, so akavache depends on akavache.sqlite3, which depends on 1.1.8 or higher:

![image](https://user-images.githubusercontent.com/1901832/37694452-0fe9f532-2d13-11e8-9511-979cd4d17c50.png)

If there _was_ a change in behavior between 1.1.8 and 1.1.9, that would explain why it suddenly manifested for me, since I was not pinned to 1.1.8.

> When I build this csproj, I do not get x64/x86 subdirs in the build output directory

Neither do I. But I _used_ to, before 1.1.9 was released. Now I have to explicitly depend on e_sqlite (either 1.1.8 _or_ 1.1.9) in order to get the x64/x86 subdirs.

**Comment by ericsink** [comment] 2018-03-21 13:45
The dependency specifies "1.1.8 or higher", but that means nuget will choose 1.1.8.  It chooses the lowest version that satisfies the constraint.

I just verified this with my little test project, using the csproj mentioned in my previous comment.  The SQLitePCLRaw.core.dll in the output directory is the one from 1.1.8.  

I wondering if the different behavior you are observing was caused by Something Else, not by a difference between SQLitePCLRaw 1.1.8 and 1.1.9.

**Comment by kentcb** [comment] 2018-03-22 03:12
Hmm, well, color me confused. I'm at a loss at this point. I'd have to slowly strip down the project in which I can repro in order to help further. Alas, it's a project that's in support, not mainline, so it's simply not going to be feasible.

I'm happy for you to close this if you like. At least I have a straightforward fix now.

**Comment by ericsink** [comment] 2018-03-22 16:13
Yeah, plenty of confusion here.  :-)

I'll go ahead and close this for lack of evidence, but feel free to reopen if the issue needs more discussion.

**Closed by ericsink** 2018-03-22 16:13 UTC
