### ISSUE TITLE
Error: NUTC303B:Internal Compiler Error: Method 'instance System.Int32 SQLitePCL.ISQLite3Provider.sqlite3_stmt_isexplain(SQLitePCL.sqlite3_stmt)' is missing implementation

### ISSUE THREAD

**Issue by spainb** [ericsink/SQLitePCL.raw#373] opened 2020-10-08 20:24 UTC
When building a Xamarin Forms UWP project which uses sqlite-net-sqlcipher, I am receiving the following error:

(BuildNativePackage target) -> 
2020-10-08T15:06:42.6133145Z   C:\Users\VssAdministrator\.nuget\packages\microsoft.net.native.compiler\2.2.8-rel-28605-00\tools\Microsoft.NetNative.targets(801,5): error : Error: NUTC303B:Internal Compiler Error: Method 'instance System.Int32 SQLitePCL.ISQLite3Provider.sqlite3_stmt_isexplain(SQLitePCL.sqlite3_stmt)' is missing implementation on type 'SQLitePCL.SQLite3Provider_e_sqlite3' from assembly 'SQLitePCLRaw.provider.e_sqlite3' while loading type 'SQLitePCL.SQLite3Provider_e_sqlite3'. while computing compilation roots. [D:\a\1\s\eT2\eT2.UWP\eT2.UWP.csproj]
2020-10-08T15:06:42.6138316Z   C:\Users\VssAdministrator\.nuget\packages\microsoft.net.native.compiler\2.2.8-rel-28605-00\tools\Microsoft.NetNative.targets(801,5): error : ILT0005: 'C:\Users\VssAdministrator\.nuget\packages\runtime.win10-x86.microsoft.net.native.compiler\2.2.8-rel-28605-00\tools\x86\ilc\Tools\nutc_driver.exe @"D:\a\1\s\eT2\eT2.UWP\obj\x86\UWP-Eval-Release\ilc\intermediate\MDIL\eT2.UWP.rsp"' returned exit code 1 [D:\a\1\s\eT2\eT2.UWP\eT2.UWP.csproj]

I saw you had a similar issue in the past about a different API function.  Like that issue, I am only seeing the issue when Compile with .NET Native tool chain is checked.

In the previous issue, your short term resolution pointed to AppCenter.Crashes.  I do have AppCenter Crashes and Analytics enabled - removing any references to AppCenter.Crashes in Nuget and code, however, did not resolve the issue.

I am not seeing the issue when compiling in Android or iOS.

I do not see the issue when using sqlite-net-pcl.

I see it when building locally (VS 16.7.4).  I see it when building using Azure Pipelines.

I'd be glad to give you any additional information or diagnostics to help out.

-Bill Spain

**Comment by ericsink** [comment] 2020-10-08 20:29
Duplicate of #372

**Closed by ericsink** 2020-10-08 20:29 UTC
