### ISSUE TITLE
Native bundled Sqlite is unreliable

### ISSUE THREAD

**Issue by Dynogic** [ericsink/SQLitePCL.raw#97] opened 2016-09-12 06:04 UTC
Hi there,

I have previously updated to the latest SQLite-net-pcl (https://github.com/praeclarum/sqlite-net) that uses SQLitePCL.raw 0.9.3 from the old SQLIte-net-pcl 1.1.1. To my knowledge, 0.9.3 makes use of a custom built Android sqlite.so libraries. My users have noticed random rollbacks in their databases (such as reverting a thread unread indicator back to its default value) on the new custom built libraries compared to the old 1.1.1 that just uses the system sqlite.so. Reverting to the old 1.1.1 is a confirmed fix for these users - they've not had an issue since. I do not reference Mono.Sqlite at all either - there are also no sign of Xamarin's sqlite_xamarin.so libraries, so I can't imagine the corruptions happening because of multiple libraries loaded in.

I've checked how I'm accessing these databases... every time an access is made to them, there is a proper C# lock mechanism put in place, along with the SQLiteConnection object wrapped in a using statement.

Any guidance to what to do? Seems like a few weeks ago you recompiled the custom built libraries. There's not yet a nuget to incorporate these changes though. Perhaps this resolves the issue?

Thanks,
Jake.

**Comment by ericsink** [comment] 2016-09-12 13:04
A mystery.

I agree that this is probably not any sort of multiple-sqlite corruption issue.  In fact, I doubt it is a corruption of any kind.  More likely, the sqlite lib is simply interacting with your app a little differently and so some data isn't getting committed.

I am also skeptical that the recompile of the custom build sqlite will help. Unless it is some sort of thread safety compile setting issue.

I will look at how the custom build is compiled to see if I spot anything wrong.

But the most helpful thing would be to have some kind of info from your app on what went wrong.  If this isn't working as it did before, then at some point, sqlite returned an error code.  Is the app giving any sort of errors or exceptions when things go wrong?

**Comment by Dynogic** [comment] 2016-09-12 18:43
Well, if the Sql connection fails to open, then a new one is created. Here's my wrapper code around sqlite-net-pcl: https://gist.github.com/Dynogic/9491ec2fc9a047169afb3cc9cbf6fdcd

The `public SqlDatabase(string fileLocation, bool deleteAndRecreateOnException)` where deleteAndRecreateOnException is false is only called in one particular database where the code will deal with the Failed flag and defer transactions. This case we can ignore.

Users aren't experiencing complete annihilation of the databases though. I can confirm this as well from the logs they've sent me (i.e there is no log as indicated in the Gist). As previously mentioned, only some of the data is lost... I assume being some sort of corruption and Sqlite having to "fix" certain portions of the database.

Other than that information, I really have no idea what else I can do to get a better diagnosis. Perhaps there is an event I can listen to that can output Sqlite errors - to which I can print them in the log?

It's also worth mentioning that there are at least 10 separate database files. One for conversation settings, one for the message sending queue manager, etc. Perhaps two can be open simultaneously with Sqlite-net-pcl and cause weird things to happen? It should be mentioned once again that no one database file can have SQL transactions happening both at once with the locks wrapped around my SqlDatabase wrapper.

**Comment by ericsink** [comment] 2016-09-12 19:51
> only some of the data is lost... I assume being some sort of corruption and Sqlite having to "fix" certain portions of the database

This is just unlikely.  I can't bring myself to assume the data was committed and then somehow lost, because I can't think of any ways that could happen, especially without clear evidence of the crime.  It's much easier for me to assume it was never actually committed, because there are lots of ways that could happen.

OTOH, I'll admit that I'm having trouble figuring out why a simple swap of a custom SQLite for the system SQLite would cause such a thing to happen.  But it's still a much better theory to start with, IMHO.

But if you have or can gather evidence that the lost rows actually did get committed and then somehow disappeared, that would obviously be very interesting.

Does your app do all of its interactions with sqlite through that SQLDatabase<T> class that you posted in the gist?

What version of android is in play here?  More to the point, I am wondering if you know which version of SQLite was being used before, when it was being obtained from the OS.  (I don't immediately see how this would matter, but still...)

Can you reproduce this problem?  Or is it simply something you are hearing from your users?

**Comment by ericsink** [comment] 2016-09-13 13:10
I have a theory.  If I provide you a new libesqlite3.so, can you drop it in and test it?

This is somewhat dependent on the answer to this question from above:

> Can you reproduce this problem? Or is it simply something you are hearing from your users?

**Comment by ericsink** [comment] 2016-09-13 13:36
OK, try updating the following nuget package:

SQLitePCL.plugin.sqlite3.android

to version:

0.9.4-pre2

**Comment by Dynogic** [comment] 2016-09-13 23:18
> Does your app do all of its interactions with sqlite through that SQLDatabase class that you posted in the gist?

Yep.

I don't have enough data gathered to specifically say what devices are affected. The ones that reported the issue are all on Android 5.x+ however.

No, I cannot reproduce the problem myself. More likely or not, it happens to people when the app updates. But also happens at random.

I assume 0.0.4-pre2 has the new libesqlite3.so? If so, yes, I can definitely send out a version to those affected and they'll monitor the situation for us.

**Comment by Dynogic** [comment] 2016-09-13 23:19
Thanks for your efforts to help resolve this issue!

**Comment by Dynogic** [comment] 2016-09-13 23:20
As I side note, perhaps we can investigate how Android builds SQLite and copy-over the build configuration?

**Comment by Dynogic** [comment] 2016-09-13 23:26
https://android.googlesource.com/platform/external/sqlite/+/master/dist

Perhaps one should just use these sources (along with the Android.mk file) to build the libsqlite that's distributed with SQLitePCL.raw?

**Comment by ericsink** [comment] 2016-09-14 03:39
Yes, the new pkg includes a new libesqlite3.so. 

Its main difference is in adding one compile flag which I found present in the android system SQLite build config. Setting the temp store value to 3. I believe this setting is probably important for android, and may even be the cause of symptoms like the ones you are seeing. 

No, I don't want to copy the build config exactly, nor do I want to use the exact same source code from the android tree. At least not for the e_sqlite3 packages. I want to keep them all similar for cross platform apps.

**Comment by Dynogic** [comment] 2016-09-14 04:50
Alright. Will give this new nuget a try! I'll report back on my findings.

**Comment by ericsink** [comment] 2016-09-20 15:57
Any update on this?

**Comment by Dynogic** [comment] 2016-09-22 22:01
Hi @ericsink , will send out a custom APK by tonight for them to test!

**Comment by Dynogic** [comment] 2016-09-23 22:35
Hi, looks like you did a pretty big update this week. I've checked the hashes on the included nuget, https://www.nuget.org/packages/SQLitePCLRaw.lib.e_sqlite3.android/, and they match with what's in the master branch of this GitHub. 

> SHA1(/Users/jake/Desktop/com.disa-0.9.9-305-telegram-sqlite-fix/lib/armeabi/libe_sqlite3.so)= 62f80ef9418b4f671192c07d0fd1db5cc2f88dbe

I've dispatched the update to a select group of people who will follow-up during the weekend.

**Comment by ericsink** [comment] 2016-09-23 22:44
:thumbsup:

**Comment by Dynogic** [comment] 2016-09-28 22:25
Hi, issue looks resolved. No one is having issues anymore :)

**Closed** 2016-09-29 00:20 UTC
