### ISSUE TITLE
create_collation bug with multiple connections (iOS)

### ISSUE THREAD

**Issue by dominik-weber** [ericsink/SQLitePCL.raw#42] opened 2015-03-14 16:10 UTC
When using multiple connections I have to call raw.sqlite3_create_collation for every connection to register the collation functions. Doing so I get random NullPointer exceptions from SQLite3Provider.collation_hook_bridge_impl at a later point.

I think I narrowed the problem down to the following (correct me if I'm wrong):
The SQLite3Provider class is implemented as a singleton (static member _imp of class raw) which contains a Dictionary _collation_hooks. Now every time create_collation is called (regardless of the connection or db object) the old collation hook of the _collation_hooks dictionary is released and a new one is created.
So when first connection1 and then connection2 are created and the collations are registered in this order, connection1 contains a collation hook which was released and is therefore unusable.

Another thought: As you do not lock the _collation_hooks dictionary in a critical section, have you tested opening multiple connections simultaneously from different threads? This might produce race conditions...

**Comment by bordoley** [comment] 2015-03-14 16:30
I only briefly glanced at the code but a possible solution to this would be to use a ConditionalWeakTable to map sqlite3 instances to per connection dictionaries. Regarding the concurrency question, it would probably be easier to define individual sqlite3 instances as not being threadsafe (this is what I do in pretty as well), while the ConditionalWeakTable would provide the necessary thread safety guarantees needed for creating new connections from different threads.

**Comment by bordoley** [comment] 2015-03-15 08:42
I added the following [Expando object](https://github.com/bordoley/SQLitePCL.pretty/blob/master/SQLitePCL.pretty/Expando.cs) to SQLitePCL.pretty to solve some similar problems. It's loosely based on Stephen Cleary's [connected properties](http://connectedproperties.codeplex.com/) library. The main difference is that the per object property map is not threadsafe. I can look into patching this issue this week to utilize a similar Expando object in SQLitePCL.raw, but wanted to get your impressions first before jumping in to code a fix.

**Comment by ericsink** [comment] 2015-03-15 11:36
(1)  I'm pretty sure I understand the problem.

(2)  I don't yet have a proposed solution of my own.  I would need to investigate more deeply.

(3)  I understand bordoley's proposed solution, but only at a shallow level, so I have enough confidence to say "Yes, I am interested in this", but not enough to say "Yes!  Do it!"

(4)  I assume that the same problem exists in the several other places I'm using a Dictionary to keep track of hooks.  :-(

**Comment by dominik-weber** [comment] 2015-03-15 13:58
Woah, that was a quick reply ;)
While I think bordoley's solution would be good, the ConditionalWeakTable class is only applicable for reference types, so it does not work for the IntPtrs you're using inside SQLite3Provider (and changing everything to the sqlite3 class would require a lot of changes). Another solution I propose:
Instead of using
```
Dictionary<string, collation_hook_info> _collation_hooks
```
you could use a
```
ConcurrentDictionary<IntPtr, Dictionary<string, collation_hook_info>> _collation_hooks
```
(which is threadsafe) and then clean up inside the sqlite3_close and sqlite3_close_v2 methods:
```
int ISQLite3Provider.sqlite3_create_collation(IntPtr db, string name, object v, delegate_collation func)
{
    var collation_hooks = _collation_hooks.GetOrAdd(db, p => new Dictionary<string, collation_hook_info>());
    //the rest of the method stays the same, except for using "collation_hooks" instead of "_collation_hooks"
}
```
```
int ISQLite3Provider.sqlite3_close(IntPtr db)
{
    Dictionary<string, collation_hook_info> collation_hooks;
    if (_collation_hooks.TryRemove(db, out collation_hooks))
    {
        //free everything inside collation_hooks
    }
    return NativeMethods.sqlite3_close(db);
}
```

And of course this would have to be done for collation hooks, function hooks and the commit/update hooks.
However I still think it would be worth the effort as this bug makes the SQLite.raw framework pretty much useless on iOS when you need custom collations/functions/...

**Comment by bordoley** [comment] 2015-03-15 14:25
The problem with the ConcurrentDictionary solution is that its not available in the PCL profile, and specifically is missing outright from Windows Phone 8, which I believe uses the PInvoke implementation. You can mimic it with locks but that comes with all the associated problems ConcurrentDictionary is used to avoid. You make an excellent point about IntPtr being a struct and therefore not compatible with ConditionalWeakTable . Hmm...

**Comment by dominik-weber** [comment] 2015-03-15 15:15
Hmm, I missed that. How about just using a regular Dictionary with lock(){}? As the locking would only be required when creating collations / closing the db connection the potential performance overhead could probably be ignored...

**Comment by ericsink** [comment] 2015-03-16 17:15
I'm going experiment with a fix based on the ideas above:

(1) One dictionary per connection
(2) lock(){}

I'll let you know how it goes.

--
E

**Comment by bordoley** [comment] 2015-03-16 17:41
You might want to consider defining a custom IConcurrentDictionary interface, and wrapping ConcurrentDictionary on platforms that support it and using locks on those that don't via ifdefs. The connected properties library I linked to above includes such an implementation that you could copy verbatim.

**Comment by dominik-weber** [comment] 2015-03-16 18:16
Eric I don't know exactly what you mean with "One dictionary per connection", but it would probably be much cleaner code if you used just one static dictionary and a helper class which contains all the connection-specific properties:
```
//used to associate connections (IntPtr) with ConnectionHooks objects
//access must be lock-ed or ConcurrentDictionary used on supporting platforms (like bordoley said)
static Dictionary<IntPtr, ConnectionHooks> _connection_hooks;


class ConnectionHooks
{
    object /*or whatever*/ commit_hook;
    //...
    Dictionary<string, object> collation_hooks;
    //...

    public void Dispose() //call this method in sqlite3_close and sqlite3_close_v2
    {
        //free all hooks
    }
}
```

**Comment by ericsink** [comment] 2015-03-16 18:24
All I meant was, in deliberately vague terms, what you were proposing.

My focus at first will be to make sure I can reproduce the behavior you are
seeing and then find a solution that fixes the problem.

--
E

**Comment by ericsink** [comment] 2015-03-16 19:36
Just to clarify something about this remark from @dominik-weber 

"as this bug makes the SQLite.raw framework pretty much useless on iOS when you need custom collations"

As far as we know, the following two statements are true, right?

(1)  The bug is not specific to iOS.

(2)  The bug doesn't happen when only one SQLite connection is in play.

Thanks.

**Comment by ericsink** [comment] 2015-03-16 20:28
OK, maybe I actually don't understand this bug.  I have added test_collation_2() and test_collation_3() to src/cs/test_cases.cs, and neither of them reproduces the problem.  @dominik-weber can you look at the code for these test cases and see if you can spot why they do not bring about the "random NullPointer exceptions from SQLite3Provider.collation_hook_bridge_impl" that you are seeing?  Thanks.

**Comment by bordoley** [comment] 2015-03-16 20:31
I haven't tested this but one case I can think of is adding two different
collation sequences to two different db connections with the same name.

**Comment by dominik-weber** [comment] 2015-03-16 22:50
@ericsink I was unfortunately not yet able to create a test case to reproduce the problem. I have a fairly large application which currently uses SQLitePCL and I'm trying to switch to SQLitePCL.raw. I got the exceptions after I changed my code to use SQLitePCL.raw, and I can kind-of reproduce it by working with the app for a little while...
In the mean time I found another way to test if the collations work (it doesn't produce the NullReference exception though):

```
            string res1, res2, res3;

            using (var c1 = ugly.open(path))
            {
                c1.create_collation("col", null, (o, p1, p2) => string.Compare(p1, p2));
                res1 = c1.query_scalar<string>("select name from applications order by name collate col");

                using (var c2 = ugly.open(path))
                {
                    c2.create_collation("col", null, (o, p1, p2) => string.Compare(p2, p1));
                    res2 = c2.query_scalar<string>("select name from applications order by name collate col");
                }

                res3 = c1.query_scalar<string>("select name from applications order by name collate col");
            }
```
Notice the changed parameter order for the collation of c2 (c1 sorts ascending while c2 sorts descending).
When running this code you will find that res2==res3 instead of the expected result res1==res3

**Comment by dominik-weber** [comment] 2015-03-16 23:24
I installed an update for Xamarin.iOS which replaced the NullReference exception with a ArgumentException "GCHandle value belongs to a different domain". After asking Google I found out that this basically means the same thing - a GCHandle (the commit_hook_info handle) was accessed after it was freed.
(http://forums.xamarin.com/discussion/925/what-is-causing-gchandle-value-belongs-to-a-different-domain, check out the comment from RolfBjarneKvinge)

I think this exception is quite hard to test as it may depend on the VMs memory allocation.
BUT I found a way to reproduce the bug with Xamarin iOS (classic api) on iOS Simulator (iPad 2, iOS 8.2). It turned out we just have to allocate some memory:

```
            string res1, res2, res3;

            using (var c1 = ugly.open(path))
            {
                c1.create_collation("col", null, (o, p1, p2) => string.Compare(p1, p2));
                res1 = c1.query_scalar<string>("select name from applications order by name collate col");

                for (int i = 0; i < 10000; i ++)
                    GCHandle.Alloc(new byte[10000]);

                using (var c2 = ugly.open(path))
                {
                    c2.create_collation("col", null, (o, p1, p2) => string.Compare(p2, p1));
                    res2 = c2.query_scalar<string>("select name from applications order by name collate col");
                }

                res3 = c1.query_scalar<string>("select name from applications order by name collate col");
            }
```
When executing this code the line "res3 = ... " throws the GCHandle exception.

**Comment by ericsink** [comment] 2015-03-17 17:21
I have added test_collation_4(), which is basically the same as what @dominik-weber suggested above (the one where res1 != res3, not the one with the GCHandle exception).  This test currently fails (which is good).  I have also added test_collation_5() which is the same test except using static methods instead of lambdas.  It fails too.

I don't yet have a clean test to repro the memory-related aspect, but I can move forward with a fix for the main issue.

**Comment by dominik-weber** [comment] 2015-03-17 17:45
Great, thanks!
I *think* when you have a lambda which doesn't access any variables or class members it is compiled as a static function, so these *should* be the same.

Probably a good additional test would be like
```
var x = new Func<string, string, int>((p1, p2) => string.Compare(p1, p2));
sqlite3_create_collation(db, (o, p1, p2) => x(p1, p2));
```
or something similar, just to check if x gets garbage collected

**Comment by ericsink** [comment] 2015-03-25 16:39
Update just to say that I have not forgotten about this and will get it done as soon as possible.  I got a little sidetracked.  :-)

**Comment by ericsink** [comment] 2015-03-31 19:13
OK, I've finally pushed a fix for this, and I am inviting code review from you guys.

util.cs contains the new class called hooks which manages thread safety and another class called info which keeps a class which contains all the hooks for a given SQLite db connection.

Both sqlite3_pinvoke.cs and sqlite3_cppinterop.cs use this new functionality.  Everywhere they need to deal with a hook function, they request the info object for that connection and use it instead of the previous approach.

This has been implemented for all NINE different kinds of hook functions.

The info object for a connection is removed when that connection is closed, to make sure that another connection which happens to reuse the same IntPtr does not reuse the hooks info object.

Apologies in advance for the poor naming of these new things.  I should at least rename info.  That's lame.

Even greater apologies for the indentation issues which seem to be getting worse every time I make a commit.  I need to run an autoindent tool on all this code, but there never seems to be a good time to do that, since it'll destroy the ability to diff across the barrier.  :-(

With those caveats aside, hopefully I've got the code in place to resolve this issue.

Thanks for your patience.

**Comment by bordoley** [comment] 2015-04-01 04:56
I'll go through the commit and add detailed comments if I see anything. 

Architecturally did you consider changing the layering such that the ISQLite3Provider methods would accept the pointer wrappers (sqlite3, etc.) instead of the raw the IntPtrs? This would allow you to hang the callbacks off the sqlite3 instances as properties similarly to what you are doing with the info class and then maintain a single mapping of IntPtrs to sqlite3 instances. This would also make implementing functions such as sqlite3_collation_needed possible.

Also I'd prefer if a the IntPtr to Info Dictionary was implemented using ConcurrentDictionary on platforms that support it. While I don't expect most users to encounter issues due to locking, SQLite generally (according to my reading of the documentation) provides good isolation between db instances, and it would be good for raw not to introduce additional concurrency concerns for users. In the future, we could even consider depending on the nuget version of [System.Collections.Concurrent](https://www.nuget.org/packages/System.Collections.Concurrent/4.0.10-beta-22605) for the windows phone implementation.

Related to your last point re: formatting, in general I find the code base hard to work with within visual studio/xam studio. Specifically the source files are quite long and I've actually ran into issues where trying to edit the code in VS caused VS to crash or hang. That said if you are primarily using VIM/Emacs I can understand the preference. If I was to reorg the code I would probably probably break up sqlite3_pinvoke.cs into several files, using partial classes to segregate both SQLite3Provider and NativeMethods by function. This preference has to do with how I use tabs in the IDE to jump around between source files.

**Comment by ericsink** [comment] 2015-04-01 15:27
I was just trying to fix a [somewhat awful] bug without making any major changes.  Changing the layering would be kind of an overhaul.  Risk of breaking something else would be quite high.

More on my perspective on the risk of changes:  http://ericsink.com/articles/Four_Questions.html

FWIW, I have often wished that sqlite provided a way to store one void* pointer inside a sqlite3 conn object.  :-)

I have not yet looked at the source to ConcurrentDictionary, but I assume it would introduce the same "additional concurrency concerns for users" as my simple lock(), while simultaneously adding a package dependency.

If it makes you feel any better, the code is hard to work with within Vim as well.  I find myself switching back and forth between several different editing environments, and things have gotten messy, so I wanted to acknowledge the mess and apologize for it.  But I still don't like to mix functionality changes with formatting changes too much.

**Comment by bordoley** [comment] 2015-04-01 17:37
1) Re: Architecture, I totally get that rationale. I wanted tor bring it up though to at least consider it as an option for the future. With the current approach it might be useful to also maintain a weakref to the sqlite3 instance in the info class, so that we can go ahead and implement sqlite3_collation_needed etc.

2) ConcurrentDictionary internally uses one lock per bucket, so it avoids blocking read/writes across different keys in the dictionary in the common case [*]. Almost all of the supported platforms support it natively (iOS, Android, Net45) within the System.Collections.Concurrent namespace. The lone exception is win phone and in that case i was proposing to follow the bait and switch model in the short term using the locking technique you've implemented, and then consider in the long term switching to the dependent package once its out of beta.

3) Definitely agree that formatting/organization changes can wait and should be separate.

[*] For more detail see: https://www.simple-talk.com/blogs/2012/02/22/inside-the-concurrent-collections-concurrentdictionary/

**Comment by dominik-weber** [comment] 2015-04-01 22:15
@ericsink thanks for the update!
Just looking at your code it seems fine, one thing to think about though: collation/function names in SQLite are case insensitive (at least to some degree, as SQLite doesn't understand foreign languages), where your implementation uses a case sensitive Dictionary. I don't think this is a real problem as it would "only" allow some pointers to still be in memory that aren't used by SQLite anymore, but as you only have a finite many options to upper/lowercase function names the possible memory overhead would also be finite (and removed once the connection is closed). I currently can't imagine a clean way of resolving this issue as C# doesn't have a nocase comparison which works like the one SQLite uses.

Could you please also upload an updated nuget package so I can test the code with my application?

**Comment by bordoley** [comment] 2015-04-02 05:12
Can the case insensitivity issue be resolved by calling name.ToLower(CultureInfo.InvariantCulture) on the keys during insert and retrieval? Also doesn't SQLite only use case insensitivity when the name is not quoted? Might need to consider this case when determining if the name should be matched case insensitively or not.

**Comment by dominik-weber** [comment] 2015-04-02 12:36
I'm not too sure about quotes, but using ToLower or the more elegant version of using the ```new Dictionary<>(StringComparer.OrdinalIgnoreCase)``` constructor would be very wrong as C# for example compares Ä and ä to be the same (I'm from germany ;)) where SQLite does only nocase letters A through Z. So you would again end up having released pointers which could still be in use.
Using the case sensitive comparison you at least eliminate the worst case of invalid active pointers while still having the less severe problem of probably having some still alive but no longer in use pointers.

It would probably be good to add a comment to the source code which explains this problem though.

**Comment by ericsink** [comment] 2015-04-02 14:21
Version 0.8.0-pre2 has been pushed to nuget.

**Comment by bordoley** [comment] 2015-04-02 17:09
I updated to 0.8.0-pre2 and think I've found a bug (one of my sqlitepcl.pretty tests is failing with a null reference exception).

I think in ISQLite3Provider.sqlite3_close(IntPtr db) the order of operations should be reversed such that the hooks are freed after the datatabase is closed, see below:

```csharp
int ISQLite3Provider.sqlite3_close(IntPtr db)
{
    int rc;
    rc = NativeMethods.sqlite3_close(db);
    hooks.removeFor(db);
    return rc;
}
```

The SQLitePCL.pretty test that is failing is this:

```csharp
 
public void TestIsAutoCommit()
 {
     using (var db = SQLite3.OpenInMemory()) 
     {
            Assert.True(db.IsAutoCommit);
            db.Execute("BEGIN TRANSACTION;");
            Assert.False(db.IsAutoCommit);
        }
    }
}
```

The reason it is failing is that SQLitePCL.pretty exposes the Rollback hook as a C# event on IDatabaseConnection instances. Under the covers, the underlying implementation at construction time registers a rollback hook with SQLite that then publishes the event. 

In the above test, the call to dispose on the db instance var, results in a corresponding call to sqlite3_close(). Since there is a hanging transaction a rollback hook call is made, but SQLitePCL.raw has already released the hooks, so I get a null pointer.

The stack trace is below:
```
Result Message:	System.NullReferenceException : Object reference not set to an instance of an object.
Result StackTrace:	
at SQLitePCL.SQLite3Provider.rollback_hook_bridge_impl(IntPtr p)
   at SQLitePCL.SQLite3Provider.NativeMethods.sqlite3_close(IntPtr db)
   at SQLitePCL.SQLite3Provider.SQLitePCL.ISQLite3Provider.sqlite3_close(IntPtr db)
   at SQLitePCL.raw.sqlite3_close(sqlite3 db)
   at SQLitePCL.pretty.SQLiteDatabaseConnection.Dispose(Boolean disposing) in y:\Desktop\Projects\SQLitePCL.pretty\SQLitePCL.pretty\DatabaseConnection.cs:line 1162
   at SQLitePCL.pretty.SQLiteDatabaseConnection.Dispose() in y:\Desktop\Projects\SQLitePCL.pretty\SQLitePCL.pretty\DatabaseConnection.cs:line 1149
   at SQLitePCL.pretty.tests.SQLiteDatabaseConnectionTests.TestIsAutoCommit() in y:\Desktop\Projects\SQLitePCL.pretty\SQLitePCL.pretty.tests\DatabaseConnectionTests.cs:line 251
```

**Comment by ericsink** [comment] 2015-04-02 17:55
I daresay you are correct.  Nice catch.  I'll fix.

E

**Comment by ericsink** [comment] 2015-04-02 18:55
0.8.0-pre3 (with a fix for the most recent problem above) is now pushed to nuget.

**Comment by bordoley** [comment] 2015-04-03 03:25
My tests are passing now.

**Comment by dominik-weber** [comment] 2015-04-07 14:10
0.8.0-pre3 seems to be working fine with my application, I'll let you know if any bugs are reported by the users. Thanks for your good work! ;)

**Closed** 2015-07-17 13:50 UTC
