### ISSUE TITLE
Xamarin.Android: System.DllNotFoundException

### ISSUE THREAD

**Issue by inforithmics** [ericsink/SQLitePCL.raw#299] opened 2019-10-10 13:31 UTC
There is an issue with sqlite-net v1.7.302-beta that it doesn't work on android

https://github.com/praeclarum/sqlite-net/issues/882

Could there be a missing dependency for android in SQLKitePclRaw.bundle_green

**Comment by ericsink** [comment] 2019-10-10 13:41
Hmmm.  Yeah, the nuspec for bundle_green does look kinda wrong.  Thanks for the bug report.  I'll get this fixed as soon as I can.

**Comment by ericsink** [comment] 2019-10-18 14:39
I just pushed up version 2.0.2-pre20191018090318 to nuget.org, which contains a fix for this problem.

**Comment by drodriguesaar** [comment] 2019-10-18 20:25
@ericsink Thanks, just got this error after updating my package reference.

**Comment by ericsink** [comment] 2019-10-18 20:45
@drodriguesaar Please be WAY more specific.

Your comment seems to be saying that you tried the new version and it you're still getting the exact problem that is the subject of this issue, but it gives me nothing to confirm that I'm understanding you correctly, and if so, it gives me nothing to diagnose what went wrong.

Details.  Lots of details, please.

**Comment by ericsink** [comment] 2019-10-19 14:22
Update:  I've confirmed that with the latest 2.0.2-pre20191018090318, I can run my test suite on an actual Android device with bundle_green.

**Comment by NebulaSleuth** [comment] 2019-10-19 19:11
On My Pixel 3XL, using 2.0.2-pre20191018090318, I can launch from inside of VS 2019 (either Debug or Release).  And all is fine.  However, if I launch the app directly from the phone it crashes.
-----
```
10-19 12:07:55.434 14609 14609 D Mono    : DllImport attempting to load: 'e_sqlite3'.
10-19 12:07:55.434 14609 14609 D Mono    : DllImport error loading library '/storage/emulated/0/Android/data/com.Bingonomics.Player/files/.__override__/e_sqlite3': 'dlopen failed: library "/data/app/com.Bingonomics.Player-Xuils4tdIYCfM2_kzeb1yg==/lib/arm64//storage/emulated/0/Android/data/com.Bingonomics.Player/files/.__override__/e_sqlite3" not found'.
10-19 12:07:55.435 14609 14609 D Mono    : DllImport error loading library '/storage/emulated/0/Android/data/com.Bingonomics.Player/files/.__override__/libe_sqlite3.so': 'dlopen failed: library "/data/app/com.Bingonomics.Player-Xuils4tdIYCfM2_kzeb1yg==/lib/arm64//storage/emulated/0/Android/data/com.Bingonomics.Player/files/.__override__/libe_sqlite3.so" not found'.
10-19 12:07:55.435 14609 14609 D Mono    : DllImport error loading library '/storage/emulated/0/Android/data/com.Bingonomics.Player/files/.__override__/libe_sqlite3.so': 'dlopen failed: library "/data/app/com.Bingonomics.Player-Xuils4tdIYCfM2_kzeb1yg==/lib/arm64//storage/emulated/0/Android/data/com.Bingonomics.Player/files/.__override__/libe_sqlite3.so" not found'.

```

**Comment by ericsink** [comment] 2019-11-01 19:24
2.0.2 is out

**Closed by ericsink** 2019-11-01 19:24 UTC
